### ISSUE TITLE
OpenSense Sensor data

### ISSUE THREAD

**Issue by MiksLatvis** [mackuba/SmogWatch#2]
Hi, I'm trying to build my first Apple Watch app based on your project. I want to eventually add more features, so that user can choose the base station (or better yet data is served from closest one). I would like to use sensors from opensensemap. They have a simple API which I can query successfully from Postman, but I don't have experience getting data with swift.

I can't read these two values: `lastMeasurement.value` and `lastMeasurement.createdAt`

Could you please give tips on how to modify the KrakowPiosDataLoader.swift so that it would work with a basic JSON? Thank you.

<img width="566" alt="Screenshot 2019-05-24 at 11 29 42" src="https://user-images.githubusercontent.com/786264/58298889-1fd6da80-7e18-11e9-851a-3e8516234744.png">

**Comment by mackuba** [comment]
Hey!

Is the structure of the JSON objects under `sensors` always the same? I mean, do they always have the same set of fields e.g. `icon` as string, `lastMeasurement` with `value` as string and `createdAt` etc? I'm asking because this new Codable API I've used is kind of hard to use for objects of variable field structure.

If it's always the same, you just need to modify the structure used to parse data into (`Response` / `ResponseData` / `DataSeries` / `DataPoint`) and replace it with something that models your data: e.g. a `Response` object that has `let sensors: [Sensor]`, where a `Sensor` struct has fields `title`, `unit` etc., and then it has a `let lastMeasurement: Measurement`, where again the Measurement is another sub-type that has just two fields `value` and `createdAt`. And then in the end you parse the response using the `JSONDecoder` and extract `response.sensors[0].lastMeasurement.value`.

Alternatively, you can take the older version from https://github.com/mackuba/SmogWatch/blob/d53a1c786c88bc02d400046727a79b4dcffbb52d/SmogWatch%20WatchKit%20Extension/KrakowPiosDataLoader.swift and do it as it's done there: for every step on the way, pick a field from a dictionary and cast it with `as?` either to a `String`/`Int` or another `[String:Any]`.

Here are some intros to Codable:

- https://medium.com/xcblog/painless-json-parsing-with-swift-codable-2c0beaeb21c1
- https://blog.pusher.com/swift-4-decoding-json-codable/

And a more advanced and complete article with some more complex stuff: https://benscheirman.com/2017/06/swift-json/
